### ISSUE TITLE
How to use this package?

### ISSUE THREAD

**Issue by crazy-canux** [dlundgren/py-wmi-client#2]
Is there any doc or example?

**Comment by dlundgren** [comment]
I use it as a drop in replacement for the wmic binary that came with Samba, or you have to compile yourself (after finding it online). I got tired of trying to find the most up to date version, and so I wrote this.

wmic -A /etc/nagios3/wmic_auth.ini //ServerName "SELECT \* FROM Win32_PerfFormattedData_PerfOS_Memory"

I'll update the readme later today

**Comment by crazy-canux** [comment]
Ok, understand.
Thanks.

**Comment by dlundgren** [comment]
I updated the Readme so it includes more information
